Implemented several improvements
- Added passing of cpw command to cpw script
- Fixed spawning a shell command when service is already running
- Moved 'cpw start' and 'cpw stop' commands to cpw script
- Added a way to create custom cpw commands from the script
- Improved the custom flag code examples in cpw script

diff --git a/cpw b/cpw
--- a/cpw
+++ b/cpw
@@ -23,7 +23,7 @@ Usage: cpw {run|rm|rerun|edit|update|build|new|start|stop} <service>
     -script: edit cpw script
 "
 
-source ./script init "${@:2}"
+source ./script init "$@"
 
 check_image_existence () {
     if ! $(docker images | grep "^$1\s" -q); then
@@ -79,10 +79,10 @@ get_children () {
 }
 
 remove_containers () {
-    containers=$(docker ps -aqf ancestor="$1")
+    containers=$(docker ps -aqf ancestor="$2")
 
     if [[ -n "$containers" ]]; then
-        echo "These containers are based on $1:"
+        echo "These containers are based on $2:"
         for container in $containers; do
             docker ps -a | grep $container
         done
@@ -94,6 +94,7 @@ remove_containers () {
         if [[ "$REPLY" =~ ^[Yy]$ ]]; then
             for container in $containers; do
                 docker stop "$container"
+                source ./script postrun "$@"
                 docker rm "$container"
             done
         else
@@ -103,14 +104,14 @@ remove_containers () {
 }
 
 perform_build () {
-    remove_containers "$1"
+    remove_containers "$@"
     
-    old_image_ID=$(docker images -qf reference="$1")
+    old_image_ID=$(docker images -qf reference="$2")
     
-    echo -e "\n\n################////////\nBuilding $1"
+    echo -e "\n\n################////////\nBuilding $2"
     source ./script build "$@"
 
-    new_image_ID=$(docker images -qf reference="$1")
+    new_image_ID=$(docker images -qf reference="$2")
     
     # If the old image is not used anymore we remove it
     if [[ "$new_image_ID" != "$old_image_ID" ]]; then
@@ -123,15 +124,15 @@ perform_build () {
 
 # Recursively update parent images by rebuilding them.
 update_parent () {
-    local repo_digests=$(docker inspect --format='{{.RepoDigests}}' "$1")
+    local repo_digests=$(docker inspect --format='{{.RepoDigests}}' "$2")
     
     # We only look for parents if we hit a local image
     if [[ "$repo_digests" = '[]' ]]; then
-        parent=$(grep '^FROM' "$1"/Dockerfile | awk '{print $2}')
-        update_parent "$parent"
+        parent=$(grep '^FROM' "$2"/Dockerfile | awk '{print $2}')
+        update_parent "$1" "$parent" "${@:2}"
     fi
     
-    image_age=$(docker images --format '{{.CreatedAt}}' "$1" | awk '!($4="")')
+    image_age=$(docker images --format '{{.CreatedAt}}' "$2" | awk '!($4="")')
     image_age=$(date -d "$($image_date)" +%s)
     max_age=$(date -d "$PARENT_MAX_AGE days ago" +%s)
     
@@ -145,7 +146,7 @@ update_parent () {
             perform_build "$@"
         else
             # Remote image, we pull
-            docker pull "$1"
+            docker pull "$2"
         fi
     fi
     
@@ -153,46 +154,46 @@ update_parent () {
 }
 
 do_update () {
-    check_service_existence "$1"
-    check_image_existence "$1"
+    check_service_existence "$2"
+    check_image_existence "$2"
 
-    image_age=$(docker images --format '{{.CreatedAt}}' "$1" | awk '!($4="")')
+    image_age=$(docker images --format '{{.CreatedAt}}' "$2" | awk '!($4="")')
     image_age=$(date -d "$($image_date)" +%s)
     max_age=$(date -d "$MAX_AGE days ago" +%s)
 
     if [[ "$image_age" -lt "$max_age" ]]; then
         # Image is out of date, we first update its parents, then update it
-        parent=$(grep '^FROM' "$1"/Dockerfile | awk '{print $2}')
-        update_parent "$parent"
+        parent=$(grep '^FROM' "$2"/Dockerfile | awk '{print $2}')
+        update_parent "$1" "$parent" "${@:2}"
 
-        echo -e "\n\n################////////\nUpdating $1..."
+        echo -e "\n\n################////////\nUpdating $2..."
         source ./script update "$@"
     fi
 }
 
 do_build () {
     # If the image is remote, we pull
-    if ! $(docker-compose config --services | grep "^$1$" -q); then
-        docker pull "$1"
+    if ! $(docker-compose config --services | grep "^$2$" -q); then
+        docker pull "$2"
         if [[ $? = 0 ]]; then
             return 0
         else
-            echo "Could not pull image: $1"
+            echo "Could not pull image: $2"
             exit 1
         fi
     fi
     
-    check_service_existence "$1"
+    check_service_existence "$2"
 
     # We first need to know if the parent exists and is up to date
-    parent=$(grep '^FROM' "$1"/Dockerfile | awk '{print $2}')
+    parent=$(grep '^FROM' "$2"/Dockerfile | awk '{print $2}')
 
     if [[ -n $(docker images | grep "^$parent\s") ]]; then
         # Parent image already exists, we update it
-        update_parent "$parent"
+        update_parent "$1" "$parent" "${@:2}"
     else
         # Parent image does not exist, we build it
-        do_build "$parent"
+        do_build "$1" "$parent" "${@:3}"
     fi
 
     # Build the current image
@@ -200,54 +201,52 @@ do_build () {
 }
 
 do_run () {
-    check_service_existence "$1"
+    check_service_existence "$2"
     
-    if $(docker-compose ps "$1" | grep "Up" -q); then
-        echo "$1 is already running, spawning a shell..."
-        exec docker exec -ti "$1" bash
+    running=$(docker-compose ps "$2" | grep Up | awk '{print $1}')
+
+    if [ -n "$running" ]; then
+        echo "$2 is already running, spawning a shell..."
+        exec docker exec -ti "$running" bash
     else
         # We check if the image already exists
-        if $(docker images | grep "^$1\s" -q); then
+        if $(docker images | grep "^$2\s" -q); then
             if [[ $AUTO_UPDATE = true ]] ; then
-                do_update "$1"
+                do_update "$@"
             fi
         else
-            do_build "$1"
+            do_build "$1" "$parent" "${@:3}"
         fi
     fi
 
     source ./script prerun "$@"
-    docker-compose run "${RUN_ARGS[@]}" "$1"
+    docker-compose run "${RUN_ARGS[@]}" "$2"
     source ./script postrun "$@"
 }
 
 do_start () {
-    container=$(docker ps -aqf name="cpw_$1" | head -n 1)
-    
-    # We check if the container already exists
-    if [[ -n "$container" ]]; then
-        source ./script prestart "$@"
-        docker start -i "$container"
-        source ./script poststart "$@"
-        exit 1
+    check_service_existence "$2"
+    running=$(docker-compose ps "$2" | grep Up | awk '{print $1}')
+
+    if [ -n "$running" ]; then
+        echo "$2 is already running, spawning a shell..."
+        exec docker exec -ti "$running" bash
     else
-        do_run "$@"
+        source ./script start "$@"
     fi
 }
 
 do_stop () {
-    check_service_existence "$1"
-    container=$(docker ps -aqf name="cpw_$1" | head -n 1)
-    docker stop "$container"
-    source ./script postrun "$@"
+    check_service_existence "$2"
+    source ./script stop "$@"
 }
 
 do_rm () {
-    check_service_existence "$1"
-    check_image_existence "$1"
-    remove_containers "$1"
+    check_service_existence "$2"
+    check_image_existence "$2"
+    remove_containers "$@"
 
-    docker rmi "$1"
+    docker rmi "$2"
 }
 
 do_edit () {
@@ -277,32 +276,32 @@ case "$1" in
         ;;
 
     update)
-        do_update "${@:2}"
+        do_update "$@"
         ;;
 
     build)
-        do_build "${@:2}"
+        do_build "$@"
         ;;
 
     run)
-        do_run "${@:2}"
+        do_run "$@"
         ;;
 
     start)
-        do_start "${@:2}"
+        do_start "$@"
         ;;
 
     stop)
-        do_stop "${@:2}"
+        do_stop "$@"
         ;;
 
     rm)
-        do_rm "${@:2}"
+        do_rm "$@"
         ;;
 
     rerun)
-        do_rm "${@:2}"
-        do_run "${@:2}"
+        do_rm "$@"
+        do_run "$@"
         ;;
 
     edit)
@@ -317,7 +316,11 @@ case "$1" in
         "${EDITOR:-vi}" script
         ;;
 
-    *)
+    -h|--help|help)
         echo "$help_string"
+        ;;
+
+    *)
+        source ./script "$@"
         exit 1
 esac
