Added check for docker pull failure

diff --git a/cpw b/cpw
--- a/cpw
+++ b/cpw
@@ -194,6 +194,10 @@ recursive_build () {
         else
             # Remote image, we pull
             docker pull "$2"
+            if [[ $? != 0 ]]; then
+                echo "Could not pull image: $2"
+                exit 1
+            fi
         fi
     fi
 }
