Improved script code and comments

diff --git a/script b/script
--- a/script
+++ b/script
@@ -9,8 +9,9 @@
 #   $2 - the cpw command (run, build, update, etc.)
 #   $3 - the name of the docker-compose service
 #
-# But cpw also passes any extra arguments you give it alowing you to
-# create additional custom conditions.
+# But cpw also passes any extra arguments you give it alowing you to create
+# additional custom conditions. Basically, all the arguments you give to cpw are
+# passed here prepended with the event name as a first argument.
 #
 # This script also contains cpw configuration variables in the init section.
 ######################################!!!!######################################
@@ -59,8 +60,9 @@ if [[ "$event" = "init" ]]; then
     # is enabled.
     MAX_AGE=6
     
-    # The number of days a parent image should be rebuilt after. This check is
-    # triggered whenever the auto-update kicks-in.
+    # The number of days parent images should be rebuilt after. Whenever cpw
+    # updates or builds an image, it rebuilds its parents if they are older than
+    # this number of days.
     PARENT_MAX_AGE=22
     
     # This is an example of a volume variable which can be used by
@@ -69,8 +71,8 @@ if [[ "$event" = "init" ]]; then
     export VOLUME_DIRECTORY=/home/$SUDO_USER/volume
     
     # This is an array of the default arguments for the docker-compose run
-    # command. Removing '--rm' is not advised as the created container with not
-    # benefit from the cpw update system.
+    # command. Removing '--rm' is not advised as the created container will not
+    # benefit from the cpw update system if 'cpw start' is used over 'cpw run'.
     RUN_ARGS=( "--rm" )
 
     # This is an array of the default arguments for the docker-compose build
@@ -100,8 +102,8 @@ if [[ "$event" = "init" ]]; then
         RUN_ARGS=( "-d" )
 
         # Because the '--rm' argument is ignored in detached mode, you might
-        # want to remove the container afterwards. This could for example be
-        # done the next time cpw runs for the same profile.
+        # want to remove the containers afterwards. This could for example be
+        # done the next time 'cpw run' or 'cpw update' is used.
         containers=$(docker ps -aqf ancestor="$service")
 
         if [[ -n "$containers" && \
@@ -116,12 +118,12 @@ if [[ "$event" = "init" ]]; then
     # Here is an example of BUILD_ARGS change with a custom cpw parameter. The
     # '--no-cache' argument as been removed so running 'cpw run' or 'cpw build'
     # with the '-c' flag will build images using cached layers.
-    if [[ "${@:4}" =~ "-c" ]]; then
+    if [[ " ${@:4} " =~ " -c " ]]; then
         BUILD_ARGS=( "--force-rm" )
     fi
 
     # Add a flag to force update when running 'cpw run' or 'cpw update'.
-    if [[ "${@:4}" =~ "-u" ]]; then
+    if [[ " ${@:4} " =~ " -u " ]]; then
         MAX_AGE=0
     fi
 
@@ -213,37 +215,49 @@ elif [[ "$event" = "prerun" ]]; then
 #            # This will autoconfigure your AP on a plugged in Android phone.
 #            # It requires adb on the host and this app to be installed:
 #            # https://github.com/steinwurf/adb-join-wifi
-#            if [ -z "$(adb devices | grep 'device$')" ]; then
-#                echo "Warning: Could not access Android device."
+#            device=$(adb devices -l | grep 'transport_id' | \
+#                head -n 1 | awk '{print $2}')
+#
+#            case "$device" in
+#            unauthorized)
+#                echo "Access to Android device unauthorized"
 #                echo "You need to unlock it and allow debugging"
-#                read -p "Press enter to continue" -n 1 -r
-#                echo
-#            fi
+#                read -p "Once you are done, press Enter to continue"
+#                ;&
+#            device)
+#                app=$(adb shell pm list packages | \
+#                    grep 'steinwurf.adbjoinwifi')
 #
-#            app=$(adb shell pm list packages | grep 'steinwurf.adbjoinwifi')
-#            if [[ -n "$app" ]]; then
-#                adb shell am start -n com.steinwurf.adbjoinwifi/.MainActivity \
-#                    -e ssid "$ap_name" \
-#                    -e password_type WPA \
-#                    -e password "$ap_password"
-#                adb kill-server
-#            else
-#                echo "Could not find adb-join-wifi, AP on phone not configured"
-#                echo "You need this Android app if you want AP autoconfig:"
-#                echo "https://github.com/steinwurf/adb-join-wifi"
-#            fi
+#                if [[ -n "$app" ]]; then
+#                    adb shell am start \
+#                        -n com.steinwurf.adbjoinwifi/.MainActivity \
+#                        -e ssid "$ap_name" \
+#                        -e password_type WPA \
+#                        -e password "$ap_password"
+#                else
+#                    echo "Could not find adb-join-wifi, phone not configured"
+#                    echo "You need this Android app if you want AP autoconfig:"
+#                    echo "https://github.com/steinwurf/adb-join-wifi"
+#                fi
+#                ;;
+#            *)
+#                echo "You don't seem to have any Android phone plugged in"
+#                echo "Or you don't have USB debugging enabled"
+#                echo "Skipping Android phone AP autoconfiguration"
+#            esac
 #
-#            # This is an example of how you could use custom cpw arguments.
-#            # Unless you use 'cpw run mob noburp', AP traffic will not be
-#            # forwarded to Burp.
-#            if ! [[ "${@:4}" =~ "noburp" ]]; then
+#            adb kill-server
+#
+#            # Unless you use 'cpw run mob noburp', AP traffic will be forwarded
+#            # to Burp.
+#            if ! [[ " ${@:4} " =~ " noburp " ]]; then
 #                iptables -I INPUT 2 -p tcp \
 #                    -s 192.168.12.0/24 --dport 8080 -j ACCEPT
 #                iptables -t nat -A PREROUTING -p tcp \
 #                    -s 192.168.12.0/24 --dport 80 -j REDIRECT --to-port 8080
 #                iptables -t nat -A PREROUTING -p tcp \
 #                    -s 192.168.12.0/24 --dport 443 -j REDIRECT --to-port 8080
-#                echo "You can Bind Burp to 192.168.12.1 in invisible mode"
+#                echo "You can bind Burp to 192.168.12.1 in invisible mode"
 #            fi
 #        fi
 
@@ -252,7 +266,7 @@ elif [[ "$event" = "prerun" ]]; then
     fi
 
     # Firewall configuration example for internal network pentests
-    #if [ "$service" = "int" ]; then
+    #if [[ "$service" = "int" ]]; then
     #    iptables -I INPUT 2 -p tcp -m multiport --dports \
     #        21,25,53,80,88,110,139,143,389,443,445,587,1433,3141,4444 -j ACCEPT
     #    iptables -I INPUT 2 -p udp -m multiport --dports \
@@ -265,22 +279,21 @@ elif [[ "$event" = "prerun" ]]; then
 elif [[ "$event" = "postrun" ]]; then
 
     # Commands to run after the 'mob' service stops.
-    if [[ "$service" = "mob" ]]; then
-        #create_ap --stop "$wifi_interface"
+    #if [[ "$service" = "mob" ]]; then
+    #    create_ap --stop "$wifi_interface"
 
-        #if ! [[ "${@:4}" =~ "noburp" ]]; then
-        #    iptables -D INPUT -p tcp \
-        #        -s 192.168.12.0/24 --dport 8080 -j ACCEPT
-        #    iptables -t nat -D PREROUTING -p tcp \
-        #        -s 192.168.12.0/24 --dport 80 -j REDIRECT --to-port 8080
-        #    iptables -t nat -D PREROUTING -p tcp \
-        #        -s 192.168.12.0/24 --dport 443 -j REDIRECT --to-port 8080
-        #fi
-        true
-    fi
+    #    if ! [[ " ${@:4} " =~ " noburp " ]]; then
+    #        iptables -D INPUT -p tcp \
+    #            -s 192.168.12.0/24 --dport 8080 -j ACCEPT
+    #        iptables -t nat -D PREROUTING -p tcp \
+    #            -s 192.168.12.0/24 --dport 80 -j REDIRECT --to-port 8080
+    #        iptables -t nat -D PREROUTING -p tcp \
+    #            -s 192.168.12.0/24 --dport 443 -j REDIRECT --to-port 8080
+    #    fi
+    #fi
 
     # Internal network pentest cleanup example
-    #if [ "$service" = "int" ]; then
+    #if [[ "$service" = "int" ]]; then
     #    iptables -D INPUT -p tcp -m multiport --dports \
     #        21,25,53,80,88,110,139,143,389,443,445,587,1433,3141,4444 -j ACCEPT
     #    iptables -D INPUT -p udp -m multiport --dports \
